/* 
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using sib_api_v3_sdk.Client;
using sib_api_v3_sdk.Api;
using sib_api_v3_sdk.Model;

namespace sib_api_v3_sdk.Test
{
    /// <summary>
    ///  Class for testing ListsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ListsApiTests
    {
        private ListsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ListsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ListsApi
            //Assert.IsInstanceOfType(typeof(ListsApi), instance, "instance is a ListsApi");
        }

        
        /// <summary>
        /// Test AddContactToList
        /// </summary>
        [Test]
        public void AddContactToListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? listId = null;
            //AddContactToList contactEmails = null;
            //var response = instance.AddContactToList(listId, contactEmails);
            //Assert.IsInstanceOf<PostContactInfo> (response, "response is PostContactInfo");
        }
        
        /// <summary>
        /// Test CreateList
        /// </summary>
        [Test]
        public void CreateListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateList createList = null;
            //var response = instance.CreateList(createList);
            //Assert.IsInstanceOf<CreateModel> (response, "response is CreateModel");
        }
        
        /// <summary>
        /// Test DeleteList
        /// </summary>
        [Test]
        public void DeleteListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? listId = null;
            //instance.DeleteList(listId);
            
        }
        
        /// <summary>
        /// Test GetContactsFromList
        /// </summary>
        [Test]
        public void GetContactsFromListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? listId = null;
            //DateTime? modifiedSince = null;
            //long? limit = null;
            //long? offset = null;
            //var response = instance.GetContactsFromList(listId, modifiedSince, limit, offset);
            //Assert.IsInstanceOf<GetContacts> (response, "response is GetContacts");
        }
        
        /// <summary>
        /// Test GetFolderLists
        /// </summary>
        [Test]
        public void GetFolderListsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? folderId = null;
            //long? limit = null;
            //long? offset = null;
            //var response = instance.GetFolderLists(folderId, limit, offset);
            //Assert.IsInstanceOf<GetFolderLists> (response, "response is GetFolderLists");
        }
        
        /// <summary>
        /// Test GetList
        /// </summary>
        [Test]
        public void GetListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? listId = null;
            //var response = instance.GetList(listId);
            //Assert.IsInstanceOf<GetExtendedList> (response, "response is GetExtendedList");
        }
        
        /// <summary>
        /// Test GetLists
        /// </summary>
        [Test]
        public void GetListsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? limit = null;
            //long? offset = null;
            //var response = instance.GetLists(limit, offset);
            //Assert.IsInstanceOf<GetLists> (response, "response is GetLists");
        }
        
        /// <summary>
        /// Test RemoveContactFromList
        /// </summary>
        [Test]
        public void RemoveContactFromListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? listId = null;
            //RemoveContactFromList contactEmails = null;
            //var response = instance.RemoveContactFromList(listId, contactEmails);
            //Assert.IsInstanceOf<PostContactInfo> (response, "response is PostContactInfo");
        }
        
        /// <summary>
        /// Test UpdateList
        /// </summary>
        [Test]
        public void UpdateListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? listId = null;
            //UpdateList updateList = null;
            //instance.UpdateList(listId, updateList);
            
        }
        
    }

}
