/* 
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = sib_api_v3_sdk.Client.SwaggerDateConverter;

namespace sib_api_v3_sdk.Model
{
    /// <summary>
    /// Body5
    /// </summary>
    [DataContract]
    public partial class Body5 :  IEquatable<Body5>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Body5" /> class.
        /// </summary>
        /// <param name="linkContactIds">Contact ids for contacts to be linked with deal.</param>
        /// <param name="unlinkContactIds">Contact ids for contacts to be unlinked from deal.</param>
        /// <param name="linkCompanyIds">Company ids to be linked with deal.</param>
        /// <param name="unlinkCompanyIds">Company ids to be unlinked from deal.</param>
        public Body5(List<long?> linkContactIds = default(List<long?>), List<long?> unlinkContactIds = default(List<long?>), List<string> linkCompanyIds = default(List<string>), List<string> unlinkCompanyIds = default(List<string>))
        {
            this.LinkContactIds = linkContactIds;
            this.UnlinkContactIds = unlinkContactIds;
            this.LinkCompanyIds = linkCompanyIds;
            this.UnlinkCompanyIds = unlinkCompanyIds;
        }
        
        /// <summary>
        /// Contact ids for contacts to be linked with deal
        /// </summary>
        /// <value>Contact ids for contacts to be linked with deal</value>
        [DataMember(Name="linkContactIds", EmitDefaultValue=false)]
        public List<long?> LinkContactIds { get; set; }

        /// <summary>
        /// Contact ids for contacts to be unlinked from deal
        /// </summary>
        /// <value>Contact ids for contacts to be unlinked from deal</value>
        [DataMember(Name="unlinkContactIds", EmitDefaultValue=false)]
        public List<long?> UnlinkContactIds { get; set; }

        /// <summary>
        /// Company ids to be linked with deal
        /// </summary>
        /// <value>Company ids to be linked with deal</value>
        [DataMember(Name="linkCompanyIds", EmitDefaultValue=false)]
        public List<string> LinkCompanyIds { get; set; }

        /// <summary>
        /// Company ids to be unlinked from deal
        /// </summary>
        /// <value>Company ids to be unlinked from deal</value>
        [DataMember(Name="unlinkCompanyIds", EmitDefaultValue=false)]
        public List<string> UnlinkCompanyIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Body5 {\n");
            sb.Append("  LinkContactIds: ").Append(LinkContactIds).Append("\n");
            sb.Append("  UnlinkContactIds: ").Append(UnlinkContactIds).Append("\n");
            sb.Append("  LinkCompanyIds: ").Append(LinkCompanyIds).Append("\n");
            sb.Append("  UnlinkCompanyIds: ").Append(UnlinkCompanyIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Body5);
        }

        /// <summary>
        /// Returns true if Body5 instances are equal
        /// </summary>
        /// <param name="input">Instance of Body5 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Body5 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LinkContactIds == input.LinkContactIds ||
                    this.LinkContactIds != null &&
                    this.LinkContactIds.SequenceEqual(input.LinkContactIds)
                ) && 
                (
                    this.UnlinkContactIds == input.UnlinkContactIds ||
                    this.UnlinkContactIds != null &&
                    this.UnlinkContactIds.SequenceEqual(input.UnlinkContactIds)
                ) && 
                (
                    this.LinkCompanyIds == input.LinkCompanyIds ||
                    this.LinkCompanyIds != null &&
                    this.LinkCompanyIds.SequenceEqual(input.LinkCompanyIds)
                ) && 
                (
                    this.UnlinkCompanyIds == input.UnlinkCompanyIds ||
                    this.UnlinkCompanyIds != null &&
                    this.UnlinkCompanyIds.SequenceEqual(input.UnlinkCompanyIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LinkContactIds != null)
                    hashCode = hashCode * 59 + this.LinkContactIds.GetHashCode();
                if (this.UnlinkContactIds != null)
                    hashCode = hashCode * 59 + this.UnlinkContactIds.GetHashCode();
                if (this.LinkCompanyIds != null)
                    hashCode = hashCode * 59 + this.LinkCompanyIds.GetHashCode();
                if (this.UnlinkCompanyIds != null)
                    hashCode = hashCode * 59 + this.UnlinkCompanyIds.GetHashCode();
                return hashCode;
            }
        }
    }

}
