/* 
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = sib_api_v3_sdk.Client.SwaggerDateConverter;

namespace sib_api_v3_sdk.Model
{
    /// <summary>
    /// GetInboundEmailEventsEvents
    /// </summary>
    [DataContract]
    public partial class GetInboundEmailEventsEvents :  IEquatable<GetInboundEmailEventsEvents>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetInboundEmailEventsEvents" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetInboundEmailEventsEvents() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetInboundEmailEventsEvents" /> class.
        /// </summary>
        /// <param name="uuid">UUID that can be used to fetch additional data (required).</param>
        /// <param name="date">Date when email was received on SMTP relay (required).</param>
        /// <param name="sender">Sender’s email address (required).</param>
        /// <param name="recipient">Recipient’s email address (required).</param>
        public GetInboundEmailEventsEvents(Guid? uuid = default(Guid?), DateTime? date = default(DateTime?), string sender = default(string), string recipient = default(string))
        {
            // to ensure "uuid" is required (not null)
            if (uuid == null)
            {
                throw new InvalidDataException("uuid is a required property for GetInboundEmailEventsEvents and cannot be null");
            }
            else
            {
                this.Uuid = uuid;
            }
            // to ensure "date" is required (not null)
            if (date == null)
            {
                throw new InvalidDataException("date is a required property for GetInboundEmailEventsEvents and cannot be null");
            }
            else
            {
                this.Date = date;
            }
            // to ensure "sender" is required (not null)
            if (sender == null)
            {
                throw new InvalidDataException("sender is a required property for GetInboundEmailEventsEvents and cannot be null");
            }
            else
            {
                this.Sender = sender;
            }
            // to ensure "recipient" is required (not null)
            if (recipient == null)
            {
                throw new InvalidDataException("recipient is a required property for GetInboundEmailEventsEvents and cannot be null");
            }
            else
            {
                this.Recipient = recipient;
            }
        }
        
        /// <summary>
        /// UUID that can be used to fetch additional data
        /// </summary>
        /// <value>UUID that can be used to fetch additional data</value>
        [DataMember(Name="uuid", EmitDefaultValue=false)]
        public Guid? Uuid { get; set; }

        /// <summary>
        /// Date when email was received on SMTP relay
        /// </summary>
        /// <value>Date when email was received on SMTP relay</value>
        [DataMember(Name="date", EmitDefaultValue=false)]
        public DateTime? Date { get; set; }

        /// <summary>
        /// Sender’s email address
        /// </summary>
        /// <value>Sender’s email address</value>
        [DataMember(Name="sender", EmitDefaultValue=false)]
        public string Sender { get; set; }

        /// <summary>
        /// Recipient’s email address
        /// </summary>
        /// <value>Recipient’s email address</value>
        [DataMember(Name="recipient", EmitDefaultValue=false)]
        public string Recipient { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetInboundEmailEventsEvents {\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  Sender: ").Append(Sender).Append("\n");
            sb.Append("  Recipient: ").Append(Recipient).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetInboundEmailEventsEvents);
        }

        /// <summary>
        /// Returns true if GetInboundEmailEventsEvents instances are equal
        /// </summary>
        /// <param name="input">Instance of GetInboundEmailEventsEvents to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetInboundEmailEventsEvents input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Uuid == input.Uuid ||
                    (this.Uuid != null &&
                    this.Uuid.Equals(input.Uuid))
                ) && 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                ) && 
                (
                    this.Sender == input.Sender ||
                    (this.Sender != null &&
                    this.Sender.Equals(input.Sender))
                ) && 
                (
                    this.Recipient == input.Recipient ||
                    (this.Recipient != null &&
                    this.Recipient.Equals(input.Recipient))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Uuid != null)
                    hashCode = hashCode * 59 + this.Uuid.GetHashCode();
                if (this.Date != null)
                    hashCode = hashCode * 59 + this.Date.GetHashCode();
                if (this.Sender != null)
                    hashCode = hashCode * 59 + this.Sender.GetHashCode();
                if (this.Recipient != null)
                    hashCode = hashCode * 59 + this.Recipient.GetHashCode();
                return hashCode;
            }
        }
    }

}
