/* 
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = sib_api_v3_sdk.Client.SwaggerDateConverter;

namespace sib_api_v3_sdk.Model
{
    /// <summary>
    /// RemainingCreditModel
    /// </summary>
    [DataContract]
    public partial class RemainingCreditModel :  IEquatable<RemainingCreditModel>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemainingCreditModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RemainingCreditModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RemainingCreditModel" /> class.
        /// </summary>
        /// <param name="child">child (required).</param>
        /// <param name="reseller">reseller (required).</param>
        public RemainingCreditModel(RemainingCreditModelChild child = default(RemainingCreditModelChild), RemainingCreditModelReseller reseller = default(RemainingCreditModelReseller))
        {
            // to ensure "child" is required (not null)
            if (child == null)
            {
                throw new InvalidDataException("child is a required property for RemainingCreditModel and cannot be null");
            }
            else
            {
                this.Child = child;
            }
            // to ensure "reseller" is required (not null)
            if (reseller == null)
            {
                throw new InvalidDataException("reseller is a required property for RemainingCreditModel and cannot be null");
            }
            else
            {
                this.Reseller = reseller;
            }
        }
        
        /// <summary>
        /// Gets or Sets Child
        /// </summary>
        [DataMember(Name="child", EmitDefaultValue=false)]
        public RemainingCreditModelChild Child { get; set; }

        /// <summary>
        /// Gets or Sets Reseller
        /// </summary>
        [DataMember(Name="reseller", EmitDefaultValue=false)]
        public RemainingCreditModelReseller Reseller { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RemainingCreditModel {\n");
            sb.Append("  Child: ").Append(Child).Append("\n");
            sb.Append("  Reseller: ").Append(Reseller).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RemainingCreditModel);
        }

        /// <summary>
        /// Returns true if RemainingCreditModel instances are equal
        /// </summary>
        /// <param name="input">Instance of RemainingCreditModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RemainingCreditModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Child == input.Child ||
                    (this.Child != null &&
                    this.Child.Equals(input.Child))
                ) && 
                (
                    this.Reseller == input.Reseller ||
                    (this.Reseller != null &&
                    this.Reseller.Equals(input.Reseller))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Child != null)
                    hashCode = hashCode * 59 + this.Child.GetHashCode();
                if (this.Reseller != null)
                    hashCode = hashCode * 59 + this.Reseller.GetHashCode();
                return hashCode;
            }
        }
    }

}
