/* 
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = sib_api_v3_sdk.Client.SwaggerDateConverter;

namespace sib_api_v3_sdk.Model
{
    /// <summary>
    /// SendSmtpEmailMessageVersions
    /// </summary>
    [DataContract]
    public partial class SendSmtpEmailMessageVersions :  IEquatable<SendSmtpEmailMessageVersions>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendSmtpEmailMessageVersions" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendSmtpEmailMessageVersions() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendSmtpEmailMessageVersions" /> class.
        /// </summary>
        /// <param name="to">List of email addresses and names (_optional_) of the recipients. For example, [{&quot;name&quot;:&quot;Jimmy&quot;, &quot;email&quot;:&quot;jimmy98@example.com&quot;}, {&quot;name&quot;:&quot;Joe&quot;, &quot;email&quot;:&quot;joe@example.com&quot;}] (required).</param>
        /// <param name="_params">Pass the set of attributes to customize the template. For example, {&quot;FNAME&quot;:&quot;Joe&quot;, &quot;LNAME&quot;:&quot;Doe&quot;}. It&#39;s considered only if template is in New Template Language format..</param>
        /// <param name="bcc">List of email addresses and names (optional) of the recipients in bcc.</param>
        /// <param name="cc">List of email addresses and names (optional) of the recipients in cc.</param>
        /// <param name="replyTo">replyTo.</param>
        /// <param name="subject">Custom subject specific to message version .</param>
        public SendSmtpEmailMessageVersions(List<SendSmtpEmailTo1> to = default(List<SendSmtpEmailTo1>), Dictionary<string, Object> _params = default(Dictionary<string, Object>), List<SendSmtpEmailBcc> bcc = default(List<SendSmtpEmailBcc>), List<SendSmtpEmailCc> cc = default(List<SendSmtpEmailCc>), SendSmtpEmailReplyTo1 replyTo = default(SendSmtpEmailReplyTo1), string subject = default(string))
        {
            // to ensure "to" is required (not null)
            if (to == null)
            {
                throw new InvalidDataException("to is a required property for SendSmtpEmailMessageVersions and cannot be null");
            }
            else
            {
                this.To = to;
            }
            this.Params = _params;
            this.Bcc = bcc;
            this.Cc = cc;
            this.ReplyTo = replyTo;
            this.Subject = subject;
        }
        
        /// <summary>
        /// List of email addresses and names (_optional_) of the recipients. For example, [{&quot;name&quot;:&quot;Jimmy&quot;, &quot;email&quot;:&quot;jimmy98@example.com&quot;}, {&quot;name&quot;:&quot;Joe&quot;, &quot;email&quot;:&quot;joe@example.com&quot;}]
        /// </summary>
        /// <value>List of email addresses and names (_optional_) of the recipients. For example, [{&quot;name&quot;:&quot;Jimmy&quot;, &quot;email&quot;:&quot;jimmy98@example.com&quot;}, {&quot;name&quot;:&quot;Joe&quot;, &quot;email&quot;:&quot;joe@example.com&quot;}]</value>
        [DataMember(Name="to", EmitDefaultValue=false)]
        public List<SendSmtpEmailTo1> To { get; set; }

        /// <summary>
        /// Pass the set of attributes to customize the template. For example, {&quot;FNAME&quot;:&quot;Joe&quot;, &quot;LNAME&quot;:&quot;Doe&quot;}. It&#39;s considered only if template is in New Template Language format.
        /// </summary>
        /// <value>Pass the set of attributes to customize the template. For example, {&quot;FNAME&quot;:&quot;Joe&quot;, &quot;LNAME&quot;:&quot;Doe&quot;}. It&#39;s considered only if template is in New Template Language format.</value>
        [DataMember(Name="params", EmitDefaultValue=false)]
        public Dictionary<string, Object> Params { get; set; }

        /// <summary>
        /// List of email addresses and names (optional) of the recipients in bcc
        /// </summary>
        /// <value>List of email addresses and names (optional) of the recipients in bcc</value>
        [DataMember(Name="bcc", EmitDefaultValue=false)]
        public List<SendSmtpEmailBcc> Bcc { get; set; }

        /// <summary>
        /// List of email addresses and names (optional) of the recipients in cc
        /// </summary>
        /// <value>List of email addresses and names (optional) of the recipients in cc</value>
        [DataMember(Name="cc", EmitDefaultValue=false)]
        public List<SendSmtpEmailCc> Cc { get; set; }

        /// <summary>
        /// Gets or Sets ReplyTo
        /// </summary>
        [DataMember(Name="replyTo", EmitDefaultValue=false)]
        public SendSmtpEmailReplyTo1 ReplyTo { get; set; }

        /// <summary>
        /// Custom subject specific to message version 
        /// </summary>
        /// <value>Custom subject specific to message version </value>
        [DataMember(Name="subject", EmitDefaultValue=false)]
        public string Subject { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SendSmtpEmailMessageVersions {\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Params: ").Append(Params).Append("\n");
            sb.Append("  Bcc: ").Append(Bcc).Append("\n");
            sb.Append("  Cc: ").Append(Cc).Append("\n");
            sb.Append("  ReplyTo: ").Append(ReplyTo).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SendSmtpEmailMessageVersions);
        }

        /// <summary>
        /// Returns true if SendSmtpEmailMessageVersions instances are equal
        /// </summary>
        /// <param name="input">Instance of SendSmtpEmailMessageVersions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SendSmtpEmailMessageVersions input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.To == input.To ||
                    this.To != null &&
                    this.To.SequenceEqual(input.To)
                ) && 
                (
                    this.Params == input.Params ||
                    this.Params != null &&
                    this.Params.SequenceEqual(input.Params)
                ) && 
                (
                    this.Bcc == input.Bcc ||
                    this.Bcc != null &&
                    this.Bcc.SequenceEqual(input.Bcc)
                ) && 
                (
                    this.Cc == input.Cc ||
                    this.Cc != null &&
                    this.Cc.SequenceEqual(input.Cc)
                ) && 
                (
                    this.ReplyTo == input.ReplyTo ||
                    (this.ReplyTo != null &&
                    this.ReplyTo.Equals(input.ReplyTo))
                ) && 
                (
                    this.Subject == input.Subject ||
                    (this.Subject != null &&
                    this.Subject.Equals(input.Subject))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.To != null)
                    hashCode = hashCode * 59 + this.To.GetHashCode();
                if (this.Params != null)
                    hashCode = hashCode * 59 + this.Params.GetHashCode();
                if (this.Bcc != null)
                    hashCode = hashCode * 59 + this.Bcc.GetHashCode();
                if (this.Cc != null)
                    hashCode = hashCode * 59 + this.Cc.GetHashCode();
                if (this.ReplyTo != null)
                    hashCode = hashCode * 59 + this.ReplyTo.GetHashCode();
                if (this.Subject != null)
                    hashCode = hashCode * 59 + this.Subject.GetHashCode();
                return hashCode;
            }
        }
    }

}
