/* 
 * SendinBlue API
 *
 * SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :- -- -- -- -- -- --: | - -- -- -- -- -- -- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@sendinblue.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sib_api_v3_sdk.Api;
using sib_api_v3_sdk.Model;
using sib_api_v3_sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sib_api_v3_sdk.Test
{
    /// <summary>
    ///  Class for testing GetSmsCampaignStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetSmsCampaignStatsTests
    {
        // TODO uncomment below to declare an instance variable for GetSmsCampaignStats
        //private GetSmsCampaignStats instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetSmsCampaignStats
            //instance = new GetSmsCampaignStats();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetSmsCampaignStats
        /// </summary>
        [Test]
        public void GetSmsCampaignStatsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetSmsCampaignStats
            //Assert.IsInstanceOfType<GetSmsCampaignStats> (instance, "variable 'instance' is a GetSmsCampaignStats");
        }


        /// <summary>
        /// Test the property 'Delivered'
        /// </summary>
        [Test]
        public void DeliveredTest()
        {
            // TODO unit test for the property 'Delivered'
        }
        /// <summary>
        /// Test the property 'Sent'
        /// </summary>
        [Test]
        public void SentTest()
        {
            // TODO unit test for the property 'Sent'
        }
        /// <summary>
        /// Test the property 'Processing'
        /// </summary>
        [Test]
        public void ProcessingTest()
        {
            // TODO unit test for the property 'Processing'
        }
        /// <summary>
        /// Test the property 'SoftBounces'
        /// </summary>
        [Test]
        public void SoftBouncesTest()
        {
            // TODO unit test for the property 'SoftBounces'
        }
        /// <summary>
        /// Test the property 'HardBounces'
        /// </summary>
        [Test]
        public void HardBouncesTest()
        {
            // TODO unit test for the property 'HardBounces'
        }
        /// <summary>
        /// Test the property 'Unsubscriptions'
        /// </summary>
        [Test]
        public void UnsubscriptionsTest()
        {
            // TODO unit test for the property 'Unsubscriptions'
        }
        /// <summary>
        /// Test the property 'Answered'
        /// </summary>
        [Test]
        public void AnsweredTest()
        {
            // TODO unit test for the property 'Answered'
        }

    }

}
